import { Strategy } from "./_types";

export const STRATEGIES: Strategy[] = [

  // ── PREDICTION MARKETS ────────────────────────────────────────────────────
  {
    id: "fed_pause",
    name: "Fed Rate Pause",
    emoji: "🎯",
    category: "prediction",
    tags: ["Macro", "Fed", "Rates", "Binary"],
    riskTier: "high",
    minCapital: 1,
    isBinary: true,
    baseWinProb: 0.58,
    payoutMultiplier: 1.88,
    theses: [
      "Labor market softening and cooling CPI suggest the Fed will hold at the next FOMC. Futures pricing 68% chance of pause.",
      "PCE running below target two months straight. Political pressure building. Model gives 64% probability Fed stands pat.",
      "Employment data revised lower. Fed rhetoric has shifted dovish. High-conviction pause call with strong macro tailwind.",
    ],
  },
  {
    id: "btc_100k",
    name: "BTC Breaks $100K",
    emoji: "🎯",
    category: "prediction",
    tags: ["Crypto", "BTC", "Macro", "Binary"],
    riskTier: "high",
    minCapital: 1,
    isBinary: true,
    baseWinProb: 0.44,
    payoutMultiplier: 2.25,
    theses: [
      "ETF inflows accelerating. Supply shock post-halving tightening fast. On-chain model prices 48% probability of $100K touch this cycle.",
      "Institutional demand outpacing miner selling. Options market pricing in $100K by December. Asymmetric risk/reward at current levels.",
      "Coinbase premium sustained above 0.3% — US retail FOMO building. Model detects early Stage 3 bull market structure.",
    ],
  },
  {
    id: "nvda_earnings",
    name: "Nvidia Earnings Beat",
    emoji: "🎯",
    category: "prediction",
    tags: ["AI", "Tech", "Earnings", "Binary"],
    riskTier: "high",
    minCapital: 1,
    isBinary: true,
    baseWinProb: 0.64,
    payoutMultiplier: 1.78,
    theses: [
      "Data center revenue tracking 40% above consensus. Hyperscaler capex calls confirm Blackwell demand. Model gives 67% beat probability.",
      "Supply constraint easing into quarter end. Gross margins expanding on Blackwell mix shift. Consensus estimates appear too conservative.",
      "Enterprise AI deployment accelerating faster than street models. Three major cloud providers guided higher. Beat probability: elevated.",
    ],
  },
  {
    id: "soft_landing",
    name: "Soft Landing Confirmed",
    emoji: "🎯",
    category: "prediction",
    tags: ["Macro", "Fed", "Economy", "Binary"],
    riskTier: "high",
    minCapital: 1,
    isBinary: true,
    baseWinProb: 0.50,
    payoutMultiplier: 1.95,
    theses: [
      "Unemployment stable, inflation declining, GDP holding above 2%. Textbook soft landing setup. Model assigns 52% probability of market-defined soft landing.",
      "Consumer spending resilient despite rate pressure. Conference Board data confirms business confidence improving. Risk/reward attractive.",
      "Leading indicators stabilizing after 18-month decline. Yield curve beginning to un-invert. Soft landing odds rising in real-time.",
    ],
  },
  {
    id: "gold_ath",
    name: "Gold Breaks All-Time High",
    emoji: "🎯",
    category: "prediction",
    tags: ["Macro", "Gold", "Safe Haven", "Binary"],
    riskTier: "high",
    minCapital: 1,
    isBinary: true,
    baseWinProb: 0.52,
    payoutMultiplier: 1.85,
    theses: [
      "Central bank gold buying at 55-year high. Real yields peaking. Model detects classic ATH breakout setup with 54% probability.",
      "Dollar weakening on Fed pivot expectations. EM central banks diversifying reserves aggressively. ATH within striking distance.",
      "Geopolitical risk premium rising. Options market pricing in high-vol event. Gold historically outperforms in such regimes.",
    ],
  },
  {
    id: "sp500_ath",
    name: "S&P 500 Monthly ATH",
    emoji: "🎯",
    category: "prediction",
    tags: ["Equity", "Index", "Momentum", "Binary"],
    riskTier: "high",
    minCapital: 1,
    isBinary: true,
    baseWinProb: 0.55,
    payoutMultiplier: 1.75,
    theses: [
      "Breadth expanding with small caps joining large cap rally. Seasonal tailwinds. Model predicts 58% probability of new monthly ATH.",
      "Fund flows turning positive for equities. Buybacks accelerating post-earnings blackout. Institutional positioning still underweight.",
      "Macro headwinds fading. Earnings revision cycle turning positive. New ATH within 2% — probability of touch this month elevated.",
    ],
  },

  // ── CRYPTO ALPHA ──────────────────────────────────────────────────────────
  {
    id: "btc_spot",
    name: "BTC Spot Accumulation",
    emoji: "₿",
    category: "crypto",
    tags: ["BTC", "Spot", "On-Chain"],
    riskTier: "medium",
    minCapital: 1,
    minReturn: -28,
    maxReturn: 82,
    theses: [
      "MVRV ratio at historically bullish entry zone. Exchange outflows sustained. Whale wallets accumulating at current levels.",
      "Realized price support holding. Long-term holder supply at cycle high. On-chain model signals accumulation phase.",
      "Hash rate hitting all-time high — miner confidence strong. Coin days destroyed low — HODLers not selling.",
    ],
  },
  {
    id: "eth_staking",
    name: "ETH + Staking Yield",
    emoji: "Ξ",
    category: "crypto",
    tags: ["ETH", "Staking", "Yield", "DeFi"],
    riskTier: "medium",
    minCapital: 1,
    minReturn: -22,
    maxReturn: 65,
    theses: [
      "Staking yield at 4.2% annualized plus price appreciation upside. Supply permanently reduced post-merge. Asymmetric risk/reward.",
      "ETF approval catalyst on horizon. Institutional staking demand growing. Real yield play with embedded optionality.",
      "L2 fee revenue flowing to ETH holders. Deflationary pressure increasing with on-chain activity. Dual-yield structure attractive.",
    ],
  },
  {
    id: "defi_yield",
    name: "DeFi Yield Optimization",
    emoji: "🌊",
    category: "crypto",
    tags: ["DeFi", "Yield", "Liquidity"],
    riskTier: "medium",
    minCapital: 3,
    minReturn: 2,
    maxReturn: 48,
    theses: [
      "Liquidity pool APYs at 18-35% on blue-chip pairs. Impermanent loss risk manageable at current volatility. Strong risk-adjusted return.",
      "Protocol revenue at ATH across top 5 DeFi platforms. Real yield (not emissions) driving sustainable APY of 12-28%.",
      "TVL recovering post-bear market. New vault strategies automating compounding. Model optimizes across 40 protocols in real time.",
    ],
  },
  {
    id: "altcoin_momentum",
    name: "Altcoin Momentum Play",
    emoji: "🚀",
    category: "crypto",
    tags: ["Altcoin", "Momentum", "Breakout"],
    riskTier: "extreme",
    minCapital: 1,
    minReturn: -65,
    maxReturn: 220,
    theses: [
      "BTC dominance declining signals altseason rotation. Volume 3.2x 20-day average on mid-caps. Breakout pattern confirmed.",
      "Top 10 alt flow model showing capital rotation from BTC. Historical backtests show 180-day return of 240% in similar regimes.",
      "Smart money wallets accumulating AI and DePIN tokens. On-chain momentum score highest since 2021 cycle peak.",
    ],
  },
  {
    id: "memecoin_lottery",
    name: "Memecoin Roulette",
    emoji: "🐸",
    category: "crypto",
    tags: ["Meme", "Speculative", "Viral", "Extreme"],
    riskTier: "extreme",
    minCapital: 1,
    minReturn: -98,
    maxReturn: 900,
    theses: [
      "Viral narrative detected on-chain. Early wallet accumulation pattern identical to PEPE pre-launch. Lottery ticket play only.",
      "Social velocity score 8.4/10 — trending across Twitter, TG, Reddit simultaneously. Memecoin cycle historically peaks 72h after viral ignition.",
      "Whale wallet seeding detected 48 hours ago. Market cap below $5M. Either zero or life-changing — use size accordingly.",
    ],
  },
  {
    id: "crypto_neutral",
    name: "Crypto Market Neutral",
    emoji: "⚖️",
    category: "crypto",
    tags: ["Neutral", "Arb", "Low Vol"],
    riskTier: "low",
    minCapital: 2,
    minReturn: 1,
    maxReturn: 20,
    theses: [
      "Long BTC / short ETH spread trade. Historical correlation 0.92 with mean reversion on 12% divergence. Current spread at 2.3 sigma.",
      "Funding rate arb: perp funding positive at 0.08% daily. Spot/perp basis captures ~30% annualized with near-zero directional risk.",
      "CEX/DEX price discrepancy averaging 0.4% on BTC pairs. Automated arb capturing spread with sub-second execution.",
    ],
  },
  {
    id: "layer2_bet",
    name: "Layer 2 Ecosystem",
    emoji: "⚡",
    category: "crypto",
    tags: ["L2", "Scaling", "Ecosystem", "ETH"],
    riskTier: "high",
    minCapital: 2,
    minReturn: -55,
    maxReturn: 165,
    theses: [
      "L2 TVL growing 40% month-over-month. Sequencer revenue proving sustainable business model. Arbitrum and Base leading adoption.",
      "EIP-4844 dramatically reducing L2 fees — user growth accelerating. Token unlocks completing — overhang cleared.",
      "Enterprise L2 deployments from major banks signaling institutional legitimacy. Sector trading at 60% discount to ETH on TVL basis.",
    ],
  },

  // ── EQUITY MOMENTUM ───────────────────────────────────────────────────────
  {
    id: "ai_breakout",
    name: "AI Stock Breakout",
    emoji: "🤖",
    category: "equity",
    tags: ["AI", "Tech", "Momentum", "Growth"],
    riskTier: "medium",
    minCapital: 2,
    minReturn: -22,
    maxReturn: 85,
    theses: [
      "AI infrastructure buildout in innings 2-3. Hyperscaler capex accelerating. Model identifies three names with highest ROI on AI spend.",
      "Revenue ramp from AI products now showing in earnings. Multiple expansion still ahead. Consensus 12-month targets up 28% in 60 days.",
      "Technical breakout from 8-month base on expanding volume. Pattern matches pre-run structure of NVDA in 2023. High conviction.",
    ],
  },
  {
    id: "earnings_play",
    name: "Pre-Earnings Volatility",
    emoji: "💰",
    category: "equity",
    tags: ["Earnings", "Volatility", "Event", "Options"],
    riskTier: "high",
    minCapital: 2,
    minReturn: -42,
    maxReturn: 130,
    theses: [
      "IV crush trade on mega-cap tech. Options market pricing 8% move; model forecasts 14% based on channel checks. Asymmetric setup.",
      "Three companies reporting with positive earnings revision trajectories. Long volatility strategy captures outsized move potential.",
      "Supply chain data and credit card spend data suggest beats across consumer names. Pre-earnings momentum historically strong.",
    ],
  },
  {
    id: "small_cap",
    name: "Small Cap Momentum",
    emoji: "📊",
    category: "equity",
    tags: ["Small Cap", "Momentum", "Russell 2000"],
    riskTier: "high",
    minCapital: 2,
    minReturn: -38,
    maxReturn: 115,
    theses: [
      "Russell 2000 historically outperforms large caps by 12% in months 3-6 after first Fed cut. Rate sensitivity working in favor now.",
      "Breadth thrust signal triggered — 90%+ of small caps above 50-day MA for first time in 18 months. Historically leads 30% rally.",
      "M&A activity surging in micro-cap space. PE firms deploying dry powder at discounted valuations. Acquisition premium potential.",
    ],
  },
  {
    id: "sector_rotation",
    name: "Sector Rotation Signal",
    emoji: "🔄",
    category: "equity",
    tags: ["Rotation", "Sector", "Relative Value"],
    riskTier: "medium",
    minCapital: 3,
    minReturn: -18,
    maxReturn: 50,
    theses: [
      "Energy sector breaking out as tech money rotates. Oil supply constraints tightening. Sector at 30% discount to historical P/E.",
      "Healthcare defensive rotation underway. Aging demographic tailwind + GLP-1 catalyst cycle. Model identifies sector inflection.",
      "Financials benefiting from steepening yield curve. Net interest margin expansion ahead. Rotation out of utilities confirmed by flow data.",
    ],
  },
  {
    id: "options_leverage",
    name: "Options Leverage Play",
    emoji: "📉",
    category: "equity",
    tags: ["Options", "Leverage", "Calls", "Extreme"],
    riskTier: "extreme",
    minCapital: 2,
    minReturn: -85,
    maxReturn: 420,
    theses: [
      "30-day ATM call options on S&P 500 index. Implied volatility at 12-month low — cheap leverage. Breakeven requires only 4% rally.",
      "Single-name call spread on high-conviction AI name. Defined risk, 5:1 payout if model is correct. VIX at 14 makes options cheap.",
      "LEAPS on transformative tech — two-year time horizon captures full product cycle. Theta manageable at current IV environment.",
    ],
  },
  {
    id: "dividend_compound",
    name: "Dividend Compounding",
    emoji: "💎",
    category: "equity",
    tags: ["Dividend", "Compounding", "Low Vol", "Income"],
    riskTier: "low",
    minCapital: 5,
    minReturn: 2,
    maxReturn: 22,
    theses: [
      "High-yield dividend aristocrats averaging 4.8% yield with 12% average annual dividend growth. Compounding effect substantial over rounds.",
      "Covered call overlay on dividend portfolio boosts effective yield to 8-12%. Low-risk income generation with equity upside participation.",
      "Dividend reinvestment strategy with automatic quarterly rebalancing. Historical 30-year Sharpe of 0.85 — best risk-adjusted in equity universe.",
    ],
  },

  // ── QUANT / ALGO ──────────────────────────────────────────────────────────
  {
    id: "stat_arb",
    name: "Statistical Arbitrage",
    emoji: "⚙️",
    category: "quant",
    tags: ["Stat Arb", "Pairs", "Market Neutral"],
    riskTier: "very_low",
    minCapital: 2,
    minReturn: -4,
    maxReturn: 18,
    theses: [
      "17 co-integrated pairs trading at 2.5+ sigma divergence. Mean reversion historically completes within 8 trading days. High win rate.",
      "Long/short equity pair basket with sector-neutral construction. Expected alpha of 14% annualized with Sharpe above 2.0.",
      "Pairs trading on merger arb spread. Regulatory approval expected — spread collapses to zero on close. Low-risk, defined return.",
    ],
  },
  {
    id: "market_making",
    name: "Market Making Spread",
    emoji: "🏦",
    category: "quant",
    tags: ["Market Making", "Spread", "Stable"],
    riskTier: "very_low",
    minCapital: 1,
    minReturn: 1,
    maxReturn: 12,
    theses: [
      "Providing liquidity on 40 high-volume pairs. Bid-ask spread capture averaging 0.08% per round trip. Very high win rate, small per-trade P&L.",
      "Automated market making on options surface. Gamma scalping and delta hedging generating consistent premium income.",
      "Crypto order book depth providing spreads on 15 exchange pairs simultaneously. Inventory risk hedged. Captures 8-12% annualized.",
    ],
  },
  {
    id: "trend_follow",
    name: "Trend Following CTA",
    emoji: "📡",
    category: "quant",
    tags: ["CTA", "Trend", "Momentum", "Systematic"],
    riskTier: "medium",
    minCapital: 3,
    minReturn: -22,
    maxReturn: 58,
    theses: [
      "Multi-asset momentum model long 7 asset classes in confirmed uptrend. 12-month lookback Sharpe 1.4 — above median CTA performance.",
      "Systematic trend signals across equities, bonds, commodities, and crypto all aligned long. Rare convergence historically precedes outsized returns.",
      "MACD + ADX signal confluence on 4-hour and daily timeframes. Trend strength score 78/100 — model is high conviction on continuation.",
    ],
  },
  {
    id: "mean_reversion",
    name: "Mean Reversion Strategy",
    emoji: "↩️",
    category: "quant",
    tags: ["Mean Reversion", "Volatility", "Systematic"],
    riskTier: "low",
    minCapital: 2,
    minReturn: -14,
    maxReturn: 32,
    theses: [
      "Oversold RSI basket: 12 S&P 500 components at 2+ standard deviation drawdown from 90-day mean. Historical recovery rate 78%.",
      "VIX spike creating mean reversion opportunity in equity volatility. Selling premium post-spike captures 60-70% of IV premium.",
      "Cross-asset mean reversion: equity/bond correlation at extreme. Model expects normalization over next 30 days — 82% historical accuracy.",
    ],
  },

  // ── MACRO ─────────────────────────────────────────────────────────────────
  {
    id: "bonds_duration",
    name: "Long Duration Bonds",
    emoji: "📋",
    category: "macro",
    tags: ["Bonds", "Duration", "Rates", "TLT"],
    riskTier: "medium",
    minCapital: 3,
    minReturn: -28,
    maxReturn: 45,
    theses: [
      "Fed pivot pricing not complete. Long 20-year Treasuries captures the remaining 80-120bps of rate cut cycle. Duration risk well rewarded.",
      "Curve steepening trade: long 30Y / short 2Y. Historically best setup entering recession. Carry positive and capital gain potential.",
      "Real yields still above neutral. As inflation normalizes, bond prices mean-revert. TLT 30% below 2020 highs — massive value opportunity.",
    ],
  },
  {
    id: "gold_haven",
    name: "Gold Safe Haven",
    emoji: "🥇",
    category: "macro",
    tags: ["Gold", "Safe Haven", "Inflation", "DXY"],
    riskTier: "low",
    minCapital: 2,
    minReturn: -12,
    maxReturn: 38,
    theses: [
      "Central bank demand at multi-decade high. Dollar weakening into Fed cycle. Gold historically returns 25%+ in 12 months post first cut.",
      "Real interest rates turning negative — gold's strongest driver. Geopolitical risk premium building. Asymmetric hedge with equity portfolio.",
      "GLD options market pricing limited downside. Technical breakout from 3-year base. Gold/S&P ratio at historical low — reversion trade.",
    ],
  },
  {
    id: "oil_squeeze",
    name: "Oil Supply Squeeze",
    emoji: "🛢️",
    category: "macro",
    tags: ["Oil", "Energy", "OPEC", "Commodity"],
    riskTier: "high",
    minCapital: 2,
    minReturn: -32,
    maxReturn: 78,
    theses: [
      "OPEC+ cuts 1.2M bpd into falling US inventory. Backwardation steepening — physical market tighter than futures suggest. Long crude.",
      "Geopolitical risk premium understated by market. Shipping disruption adding 3-5% to effective crude price. Energy sector historically leads.",
      "Global oil demand beating IEA forecasts for 8th consecutive month. Spare capacity at 30-year low. Supply shock could drive $120/barrel.",
    ],
  },
  {
    id: "dollar_strength",
    name: "Dollar Strength Trade",
    emoji: "💵",
    category: "macro",
    tags: ["DXY", "Dollar", "FX", "Rates"],
    riskTier: "low",
    minCapital: 2,
    minReturn: -15,
    maxReturn: 35,
    theses: [
      "US growth differential vs G10 widening. Rate differential supports dollar. Long DXY via FX pairs against EUR, JPY, and GBP.",
      "Risk-off environment strengthening dollar safe haven bid. Historical analysis shows DXY rallies 8-12% in similar regime transitions.",
      "EM currency contagion risk elevated. Dollar demand from debt servicing creating structural bid. Positioned long via dollar index futures.",
    ],
  },
  {
    id: "em_highyield",
    name: "EM High Yield",
    emoji: "🌍",
    category: "macro",
    tags: ["EM", "High Yield", "FX", "Carry"],
    riskTier: "high",
    minCapital: 3,
    minReturn: -38,
    maxReturn: 72,
    theses: [
      "EM carry trade: long BRL, MXN, INR vs short JPY. Carry income of 12-18% annualized. Risk-on environment supports trade.",
      "EM sovereign spreads at 3-year wide. Fundamental deterioration overstated. Value opportunity in EM debt with dollar hedging.",
      "China stimulus cycle beginning — historically positive for EM commodity exporters. Correlation play with oil, copper, and agriculture.",
    ],
  },
];

export const STRATEGY_MAP = Object.fromEntries(STRATEGIES.map(s => [s.id, s]));
