'use client';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';

const ROOM_PRIORITY: Record<string, 'high' | 'medium' | 'low'> = {
  MOH301: 'high', MOH302: 'medium', MOH303: 'low', MOH304: 'medium',
  MOH305: 'medium', MOH306: 'low',  MOH307: 'medium', MOH308: 'high',
  MOH309: 'low',   MOH310: 'low',
};

const REPORTS = [
  { title:'Weekly Resident Summary',       date:'Dec 1–5, 2024',   type:'Clinical',      status:'Ready',    desc:'Activity levels, fall events, and Ella AI narrative digest for all 10 residents on MOH floor.' },
  { title:'Fall Incident Log',             date:'Dec 5, 2024',     type:'Incident',      status:'Ready',    desc:'Detailed log of all fall detections, response times, and resolution notes for the current day.' },
  { title:'Ella AI Narrative Export',      date:'Dec 5, 2024',     type:'AI',            status:'Ready',    desc:'Full plain-language daily summaries generated by Ella for each resident. Export as PDF or CSV.' },
  { title:'Sensor Performance Report',     date:'Dec 1–5, 2024',   type:'Technical',     status:'Ready',    desc:'IWR6843AOP uptime, detection latency, false positive rate, and signal quality per room.' },
  { title:'Compliance Snapshot',           date:'Nov 2024',        type:'Regulatory',    status:'Ready',    desc:'21 CFR 820 gap analysis progress, SaMD verification status, and risk register summary.' },
  { title:'Monthly Activity Trends',       date:'November 2024',   type:'Clinical',      status:'Ready',    desc:'30-day longitudinal view of resident activity, fall frequency, and nursing response metrics.' },
  { title:'Shift Handoff Report',          date:'Dec 5 · AM shift', type:'Operations',   status:'Ready',    desc:'Summary of events, alerts, and unresolved items for handoff from night to day nursing shift.' },
  { title:'Quarterly System Review',       date:'Q4 2024',         type:'Technical',     status:'Pending',  desc:'System-wide performance, cloud pipeline metrics, and model accuracy review. In preparation.' },
];

const TYPE_COLOR: Record<string,{bg:string;color:string}> = {
  Clinical:    { bg:'rgba(58,100,200,0.10)',  color:'#2a4fa0' },
  Incident:    { bg:'rgba(192,57,43,0.10)',   color:'#a02020' },
  AI:          { bg:'rgba(124,110,173,0.12)', color:'#5c4fa0' },
  Technical:   { bg:'rgba(120,110,100,0.10)', color:'#6b6256' },
  Regulatory:  { bg:'rgba(184,131,10,0.10)',  color:'#8a6200' },
  Operations:  { bg:'rgba(58,155,92,0.10)',   color:'#2e7d4f' },
};

export default function ReportsPage() {
  const router = useRouter();
  const [activeRoom, setActiveRoom] = useState('');
    const [now, setNow] = useState(new Date());
  useEffect(()=>{ const id=setInterval(()=>setNow(new Date()),60000); return ()=>clearInterval(id); },[]);
  useEffect(()=>{ document.body.style.background='#F0F0EE'; return ()=>{ document.body.style.background=''; }; },[]);
  const cst=new Date(now.toLocaleString('en-US',{timeZone:'America/Chicago'}));
  const DAYS=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
  const MONTHS=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  const h=cst.getHours(); const hh=h%12||12; const mm=String(cst.getMinutes()).padStart(2,'0'); const ampm=h<12?'AM':'PM';
  const crumb=`${DAYS[cst.getDay()]} · ${MONTHS[cst.getMonth()]} ${cst.getDate()} · ${hh}:${mm} ${ampm} CST`;
    const notion: React.CSSProperties = {
    '--bg':          '#F0F0EE',
    '--surface-1':   '#F7F7F5',
    '--surface-2':   '#E4E4E0',
    '--surface-3':   '#D8D8D3',
    '--line':        'rgba(30,30,28,0.08)',
    '--line-strong': 'rgba(30,30,28,0.16)',
    '--text':        '#1A1A18',
    '--text-2':      'rgba(26,26,24,0.72)',
    '--text-3':      'rgba(26,26,24,0.55)',
    '--text-4':      'rgba(26,26,24,0.40)',
    '--accent':      '#7C6EAD',
    '--accent-soft': 'rgba(124,110,173,0.14)',
    '--sage':        'oklch(0.55 0.07 155)',
    color:           'var(--text)',
  } as React.CSSProperties;

  return (
    <div className="app notion-theme" style={notion}>
            <nav className="sidebar">
        <Link href="/" style={{ textDecoration:"none", color:"inherit" }}>
          <div className="brand">
            <div className="brand-name">Ambient <em>Intelligence</em></div>
          </div>
        </Link>
        <nav className="nav-section">
          <div className="nav-label">Views</div>
            <Link href="/dashboard/overview" className={"nav-item"} style={{ textDecoration:'none', color:'inherit' }}>
              <svg className="nav-icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4">{<path d="M2.5 7L8 2.5 13.5 7v6.5h-4V10h-3v3.5h-4z" strokeLinejoin="round" />}</svg>
              Overview
            </Link>
            <Link href="/dashboard/floormap" className={"nav-item"} style={{ textDecoration:'none', color:'inherit' }}>
              <svg className="nav-icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4">{<><rect x="2.5" y="2.5" width="11" height="11" rx="1"/><path d="M2.5 7h11M7 2.5v11"/></>}</svg>
              Floor Map
            </Link>
            <Link href="/dashboard/alerts" className={"nav-item"} style={{ textDecoration:'none', color:'inherit' }}>
              <svg className="nav-icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4">{<><path d="M3.5 12.5h9l-1.5-2V7a3.5 3.5 0 10-7 0v3.5l-1.5 2z" strokeLinejoin="round"/><path d="M6.5 13.5a1.5 1.5 0 003 0" strokeLinecap="round"/></>}</svg>
              Alerts
            </Link>
            <Link href="/dashboard/reports" className={"nav-item active"} style={{ textDecoration:'none', color:'inherit' }}>
              <svg className="nav-icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4">{<><rect x="3" y="2" width="10" height="12" rx="1"/><path d="M5.5 5.5h5M5.5 8h5M5.5 10.5h3" strokeLinecap="round"/></>}</svg>
              Reports
            </Link>
            <Link href="/dashboard/analytics" className={"nav-item"} style={{ textDecoration:'none', color:'inherit' }}>
              <svg className="nav-icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4">{<><path d="M2.5 12.5h11M5 12.5V8.5M8 12.5V5M11 12.5V9.5" strokeLinecap="round"/></>}</svg>
              Analytics
            </Link>
            <Link href="/dashboard/browse" className={"nav-item"} style={{ textDecoration:'none', color:'inherit' }}>
              <svg className="nav-icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4">{<><circle cx="7" cy="7" r="4.5"/><path d="M10.5 10.5L13.5 13.5" strokeLinecap="round"/></>}</svg>
              Browse
            </Link>
        </nav>
        <nav className="nav-section">
          <div className="nav-label">Rooms</div>
            <div key="MOH 301" className="nav-item" onClick={()=>router.push('/dashboard/room/MOH301')}>
              <svg className="nav-icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4"><rect x="3" y="2.5" width="10" height="11" rx="1"/><path d="M6.5 13.5V10a1.5 1.5 0 013 0v3.5" strokeLinecap="round"/></svg>
              <span style={{ flex:1 }}>MOH 301</span>
              <span style={{ width:6, height:6, borderRadius:'50%', flexShrink:0, background: ROOM_PRIORITY['MOH301'] === 'high' ? '#FF6B6B' : ROOM_PRIORITY['MOH301'] === 'medium' ? '#FFC940' : '#3DCC91', boxShadow: ROOM_PRIORITY['MOH301'] === 'high' ? '0 0 5px #FF6B6B' : ROOM_PRIORITY['MOH301'] === 'low' ? '0 0 4px #3DCC91' : 'none' }}/>
            </div>
            <div key="MOH 302" className="nav-item" onClick={()=>router.push('/dashboard/room/MOH302')}>
              <svg className="nav-icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4"><rect x="3" y="2.5" width="10" height="11" rx="1"/><path d="M6.5 13.5V10a1.5 1.5 0 013 0v3.5" strokeLinecap="round"/></svg>
              <span style={{ flex:1 }}>MOH 302</span>
              <span style={{ width:6, height:6, borderRadius:'50%', flexShrink:0, background: ROOM_PRIORITY['MOH302'] === 'high' ? '#FF6B6B' : ROOM_PRIORITY['MOH302'] === 'medium' ? '#FFC940' : '#3DCC91', boxShadow: ROOM_PRIORITY['MOH302'] === 'high' ? '0 0 5px #FF6B6B' : ROOM_PRIORITY['MOH302'] === 'low' ? '0 0 4px #3DCC91' : 'none' }}/>
            </div>
            <div key="MOH 303" className="nav-item" onClick={()=>router.push('/dashboard/room/MOH303')}>
              <svg className="nav-icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4"><rect x="3" y="2.5" width="10" height="11" rx="1"/><path d="M6.5 13.5V10a1.5 1.5 0 013 0v3.5" strokeLinecap="round"/></svg>
              <span style={{ flex:1 }}>MOH 303</span>
              <span style={{ width:6, height:6, borderRadius:'50%', flexShrink:0, background: ROOM_PRIORITY['MOH303'] === 'high' ? '#FF6B6B' : ROOM_PRIORITY['MOH303'] === 'medium' ? '#FFC940' : '#3DCC91', boxShadow: ROOM_PRIORITY['MOH303'] === 'high' ? '0 0 5px #FF6B6B' : ROOM_PRIORITY['MOH303'] === 'low' ? '0 0 4px #3DCC91' : 'none' }}/>
            </div>
            <div key="MOH 304" className="nav-item" onClick={()=>router.push('/dashboard/room/MOH304')}>
              <svg className="nav-icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4"><rect x="3" y="2.5" width="10" height="11" rx="1"/><path d="M6.5 13.5V10a1.5 1.5 0 013 0v3.5" strokeLinecap="round"/></svg>
              <span style={{ flex:1 }}>MOH 304</span>
              <span style={{ width:6, height:6, borderRadius:'50%', flexShrink:0, background: ROOM_PRIORITY['MOH304'] === 'high' ? '#FF6B6B' : ROOM_PRIORITY['MOH304'] === 'medium' ? '#FFC940' : '#3DCC91', boxShadow: ROOM_PRIORITY['MOH304'] === 'high' ? '0 0 5px #FF6B6B' : ROOM_PRIORITY['MOH304'] === 'low' ? '0 0 4px #3DCC91' : 'none' }}/>
            </div>
            <div key="MOH 305" className="nav-item" onClick={()=>router.push('/dashboard/room/MOH305')}>
              <svg className="nav-icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4"><rect x="3" y="2.5" width="10" height="11" rx="1"/><path d="M6.5 13.5V10a1.5 1.5 0 013 0v3.5" strokeLinecap="round"/></svg>
              <span style={{ flex:1 }}>MOH 305</span>
              <span style={{ width:6, height:6, borderRadius:'50%', flexShrink:0, background: ROOM_PRIORITY['MOH305'] === 'high' ? '#FF6B6B' : ROOM_PRIORITY['MOH305'] === 'medium' ? '#FFC940' : '#3DCC91', boxShadow: ROOM_PRIORITY['MOH305'] === 'high' ? '0 0 5px #FF6B6B' : ROOM_PRIORITY['MOH305'] === 'low' ? '0 0 4px #3DCC91' : 'none' }}/>
            </div>
            <div key="MOH 306" className="nav-item" onClick={()=>router.push('/dashboard/room/MOH306')}>
              <svg className="nav-icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4"><rect x="3" y="2.5" width="10" height="11" rx="1"/><path d="M6.5 13.5V10a1.5 1.5 0 013 0v3.5" strokeLinecap="round"/></svg>
              <span style={{ flex:1 }}>MOH 306</span>
              <span style={{ width:6, height:6, borderRadius:'50%', flexShrink:0, background: ROOM_PRIORITY['MOH306'] === 'high' ? '#FF6B6B' : ROOM_PRIORITY['MOH306'] === 'medium' ? '#FFC940' : '#3DCC91', boxShadow: ROOM_PRIORITY['MOH306'] === 'high' ? '0 0 5px #FF6B6B' : ROOM_PRIORITY['MOH306'] === 'low' ? '0 0 4px #3DCC91' : 'none' }}/>
            </div>
            <div key="MOH 307" className="nav-item" onClick={()=>router.push('/dashboard/room/MOH307')}>
              <svg className="nav-icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4"><rect x="3" y="2.5" width="10" height="11" rx="1"/><path d="M6.5 13.5V10a1.5 1.5 0 013 0v3.5" strokeLinecap="round"/></svg>
              <span style={{ flex:1 }}>MOH 307</span>
              <span style={{ width:6, height:6, borderRadius:'50%', flexShrink:0, background: ROOM_PRIORITY['MOH307'] === 'high' ? '#FF6B6B' : ROOM_PRIORITY['MOH307'] === 'medium' ? '#FFC940' : '#3DCC91', boxShadow: ROOM_PRIORITY['MOH307'] === 'high' ? '0 0 5px #FF6B6B' : ROOM_PRIORITY['MOH307'] === 'low' ? '0 0 4px #3DCC91' : 'none' }}/>
            </div>
            <div key="MOH 308" className="nav-item" onClick={()=>router.push('/dashboard/room/MOH308')}>
              <svg className="nav-icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4"><rect x="3" y="2.5" width="10" height="11" rx="1"/><path d="M6.5 13.5V10a1.5 1.5 0 013 0v3.5" strokeLinecap="round"/></svg>
              <span style={{ flex:1 }}>MOH 308</span>
              <span style={{ width:6, height:6, borderRadius:'50%', flexShrink:0, background: ROOM_PRIORITY['MOH308'] === 'high' ? '#FF6B6B' : ROOM_PRIORITY['MOH308'] === 'medium' ? '#FFC940' : '#3DCC91', boxShadow: ROOM_PRIORITY['MOH308'] === 'high' ? '0 0 5px #FF6B6B' : ROOM_PRIORITY['MOH308'] === 'low' ? '0 0 4px #3DCC91' : 'none' }}/>
            </div>
            <div key="MOH 309" className="nav-item" onClick={()=>router.push('/dashboard/room/MOH309')}>
              <svg className="nav-icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4"><rect x="3" y="2.5" width="10" height="11" rx="1"/><path d="M6.5 13.5V10a1.5 1.5 0 013 0v3.5" strokeLinecap="round"/></svg>
              <span style={{ flex:1 }}>MOH 309</span>
              <span style={{ width:6, height:6, borderRadius:'50%', flexShrink:0, background: ROOM_PRIORITY['MOH309'] === 'high' ? '#FF6B6B' : ROOM_PRIORITY['MOH309'] === 'medium' ? '#FFC940' : '#3DCC91', boxShadow: ROOM_PRIORITY['MOH309'] === 'high' ? '0 0 5px #FF6B6B' : ROOM_PRIORITY['MOH309'] === 'low' ? '0 0 4px #3DCC91' : 'none' }}/>
            </div>
            <div key="MOH 310" className="nav-item" onClick={()=>router.push('/dashboard/room/MOH310')}>
              <svg className="nav-icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4"><rect x="3" y="2.5" width="10" height="11" rx="1"/><path d="M6.5 13.5V10a1.5 1.5 0 013 0v3.5" strokeLinecap="round"/></svg>
              <span style={{ flex:1 }}>MOH 310</span>
              <span style={{ width:6, height:6, borderRadius:'50%', flexShrink:0, background: ROOM_PRIORITY['MOH310'] === 'high' ? '#FF6B6B' : ROOM_PRIORITY['MOH310'] === 'medium' ? '#FFC940' : '#3DCC91', boxShadow: ROOM_PRIORITY['MOH310'] === 'high' ? '0 0 5px #FF6B6B' : ROOM_PRIORITY['MOH310'] === 'low' ? '0 0 4px #3DCC91' : 'none' }}/>
            </div>
        </nav>
        <div className="sidebar-footer">
          <span className="status-dot" />
          <span>Sensors online · MOH 301–310</span>
        </div>
      </nav>
      <main className="main">
        <header className="topbar">
          <div>
            <div className="crumb">{crumb}</div>
            <h1 className="page-title">Reports <em>&amp; Exports</em></h1>
          </div>
          <div style={{ display:'flex', gap:8, alignItems:'center' }}><button style={{ fontFamily:'var(--mono)', fontSize:11, padding:'7px 16px', borderRadius:6, border:'none', background:'var(--accent)', color:'white', cursor:'pointer' }}>+ Generate Report</button><a href="/login" className="btn btn-ghost"><svg width="14" height="14" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4"><circle cx="8" cy="5" r="2.5"/><path d="M3 13.5c0-2.5 2.2-4.5 5-4.5s5 2 5 4.5" strokeLinecap="round"/></svg>Login</a></div>
        </header>
        <div style={{ padding:'32px 40px', display:'flex', flexDirection:'column', gap:12 }}>
          {REPORTS.map((r,i)=>(
            <div key={i} style={{ background:'var(--surface-1)', border:'1px solid var(--line)', borderRadius:8, padding:'20px 24px', display:'flex', alignItems:'center', gap:20 }}>
              <div style={{ flex:1, display:'flex', flexDirection:'column', gap:6 }}>
                <div style={{ display:'flex', alignItems:'center', gap:10 }}>
                  <span style={{ fontSize:14, fontWeight:600, color:'var(--text)' }}>{r.title}</span>
                  <span style={{ display:'inline-flex', alignItems:'center', padding:'2px 8px', borderRadius:99, fontSize:10.5, fontWeight:500, background:TYPE_COLOR[r.type].bg, color:TYPE_COLOR[r.type].color, fontFamily:'var(--mono)' }}>{r.type}</span>
                  {r.status==='Pending' && <span style={{ display:'inline-flex', padding:'2px 8px', borderRadius:99, fontSize:10.5, fontWeight:500, background:'rgba(120,110,100,0.10)', color:'#6b6256', fontFamily:'var(--mono)' }}>Pending</span>}
                </div>
                <div style={{ fontSize:12.5, color:'var(--text-3)', lineHeight:1.5 }}>{r.desc}</div>
                <div style={{ fontFamily:'var(--mono)', fontSize:11, color:'var(--text-4)' }}>{r.date}</div>
              </div>
              {r.status === 'Ready' && (
                <div style={{ display:'flex', gap:8, flexShrink:0 }}>
                  <button style={{ fontFamily:'var(--mono)', fontSize:11, padding:'6px 14px', borderRadius:6, border:'1px solid var(--line)', background:'var(--surface-1)', color:'var(--text-2)', cursor:'pointer' }}>View</button>
                  <button style={{ fontFamily:'var(--mono)', fontSize:11, padding:'6px 14px', borderRadius:6, border:'none', background:'var(--accent)', color:'white', cursor:'pointer' }}>Export</button>
                </div>
              )}
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}
