// Static catalogue of regulatory standards — never modified at runtime
import type { DeviceProfile, StandardDef, TargetMarket, StandardCategory } from './data';

export const STANDARDS: StandardDef[] = [

  // ── QMS ──────────────────────────────────────────────────────────────────

  {
    id: 'iso-13485',
    number: 'ISO 13485:2016',
    title: 'Medical devices — Quality management systems',
    category: 'QMS',
    description: 'Specifies QMS requirements for design, development, production, installation, and servicing of medical devices. Incorporated into FDA QMSR effective February 2, 2026. Required by virtually all markets as the QMS baseline.',
    markets: 'global',
    priority: 'critical',
    appliesWhen: () => true,
    defaultChecklist: [
      'Define and document QMS scope including any exclusions with justification (Clause 4.1)',
      'Document quality policy and establish measurable quality objectives (Clause 5.3–5.4)',
      'Assign management representatives and define organizational authority (Clause 5.5)',
      'Conduct annual management review covering QMS performance indicators (Clause 5.6)',
      'Establish design and development control procedure with stage-gate reviews (Clause 7.3)',
      'Create design input, output, review, verification, and validation records (Clause 7.3.3–7)',
      'Establish CAPA procedure with root cause analysis and effectiveness verification (Clause 8.5.2–3)',
      'Establish supplier qualification, evaluation, and re-evaluation procedure (Clause 7.4)',
      'Conduct scheduled internal audits; document findings and resulting CAPAs (Clause 8.2.2)',
      'Maintain Device Master Record (DMR) and Device History Record (DHR) (Clause 4.2.3, 7.5)',
      'Establish customer feedback and complaint-handling procedure (Clause 8.2.1)',
    ],
  },

  // ── Risk ─────────────────────────────────────────────────────────────────

  {
    id: 'iso-14971',
    number: 'ISO 14971:2019',
    title: 'Medical devices — Application of risk management',
    category: 'Risk',
    description: 'Defines the risk management process for hazard identification, risk estimation, risk evaluation, risk control, and post-production monitoring. Integrated into ISO 13485, FDA QMSR, and EU MDR. Required across all markets and device types.',
    markets: 'global',
    priority: 'critical',
    appliesWhen: () => true,
    defaultChecklist: [
      'Document risk management plan: scope, responsibilities, risk acceptability criteria, review criteria (Clause 4)',
      'Define intended use, intended users, and all reasonably foreseeable misuse scenarios (Clause 5.2)',
      'Complete systematic hazard identification for all patient, user, and environment interactions (Clause 5.3)',
      'Estimate probability of occurrence and severity of harm for each hazard sequence (Clause 5.4)',
      'Evaluate each risk against acceptability criteria defined before evaluation begins (Clause 5.5)',
      'Implement risk controls in priority order: inherent safety → protective measures → information for safety (Clause 6)',
      'Evaluate residual risk for each implemented control; verify controls are effective (Clause 6.3–6.4)',
      'Evaluate overall residual risk; confirm benefit-risk ratio is acceptable (Clause 7)',
      'Establish post-production monitoring plan to collect and review field safety data (Clause 10)',
      'Complete risk management report referencing all risk management file activities (Clause 9)',
    ],
  },

  // ── Usability ─────────────────────────────────────────────────────────────

  {
    id: 'iec-62366-1',
    number: 'IEC 62366-1:2015+A1:2020',
    title: 'Medical devices — Usability engineering process',
    category: 'Usability',
    description: 'Specifies a process for analyzing, specifying, developing, and evaluating usability of medical devices. Usability engineering is integrated into risk management. Applies to all medical devices including IVDs. FDA HFE guidance is aligned with this standard.',
    markets: 'global',
    priority: 'critical',
    appliesWhen: () => true,
    defaultChecklist: [
      'Define intended users: experience level, training, physical and cognitive characteristics',
      'Define intended use environment: clinical setting, home, ambulance, ICU, OR, etc.',
      'Identify all user interface elements: displays, controls, alarms, packaging, labeling',
      'Conduct use-related risk analysis — identify all user interactions that could cause harm',
      'Prioritize critical tasks based on harm severity and probability of use error',
      'Conduct formative usability evaluations at key design stages (early concept through near-final)',
      'Conduct summative validation testing with representative users on all critical tasks',
      'Analyze use errors from formative testing; update design or add risk mitigations',
      'Validate labeling and IFU adequacy with target user population',
      'Document Human Factors Engineering (HFE) report covering all usability activities',
    ],
  },

  // ── Labeling ─────────────────────────────────────────────────────────────

  {
    id: 'iso-15223-1',
    number: 'ISO 15223-1:2021',
    title: 'Medical devices — Symbols for information supplied by the manufacturer',
    category: 'Labeling',
    description: 'Defines standardized symbols for medical device labeling. Recognized by FDA as a consensus standard; harmonized under EU MDR. Provides a common visual language for sterilization, storage, single-use, manufacturer ID, UDI, and more than 52 other labeling elements.',
    markets: 'global',
    priority: 'high',
    appliesWhen: () => true,
    defaultChecklist: [
      'Identify all required labeling elements: manufacturer, address, manufacturing date, expiry, lot/batch',
      'Assign symbols from ISO 15223-1 for all applicable elements; verify 5 mm minimum height',
      'Apply REF (catalog number), SN (serial number), and LOT symbols where applicable',
      'Apply UDI label with both human-readable (HRI) and AIDC (barcode / 2D matrix) formats',
      'Include CE mark (EU), UKCA (UK), or applicable conformity marks per target markets',
      'Validate label comprehension with intended users for critical safety symbols',
      'Verify labeling compliance against 21 CFR 801 (US) and MDR Annex I §23 (EU)',
    ],
  },

  // ── Software ─────────────────────────────────────────────────────────────

  {
    id: 'iec-62304',
    number: 'IEC 62304:2006+A1:2015',
    title: 'Medical device software — Software life cycle processes',
    category: 'Software',
    description: 'Defines lifecycle requirements for medical device software including SaMD. Requires safety classification (A: no harm; B: non-serious injury; C: serious injury/death) with proportionate documentation rigor. Edition 2 expected ~August 2026 with AI/ML lifecycle guidance.',
    markets: 'global',
    priority: 'critical',
    appliesWhen: p => p.hasSoftware || p.isSaMD,
    defaultChecklist: [
      'Classify software per safety classes: Class A (no harm), Class B (non-serious injury), Class C (serious injury/death)',
      'Document Software Development Plan (SDP) appropriate to safety class',
      'Establish software requirements specification (SRS) traceable to system requirements',
      'Complete software architecture design — identify all software items and interfaces',
      'Conduct unit testing with documented test cases and pass/fail criteria (Class B/C)',
      'Complete integration testing verifying software item interactions (Class B/C)',
      'Perform software system testing against full SRS requirements',
      'Establish software change management procedure with impact assessment process',
      'Document anomaly resolution process with risk-based prioritization',
      'Establish software release procedure with version identification and configuration management',
      'Document Software Maintenance Plan covering post-release updates and patches',
    ],
  },

  {
    id: 'imdrf-samd',
    number: 'IMDRF N41 / N70 / N23',
    title: 'Software as a Medical Device (SaMD) — IMDRF Framework',
    category: 'Software',
    description: 'IMDRF guidance documents defining the SaMD framework (N41), risk categorization (N70), and quality management (N23). Provides the internationally harmonized basis for SaMD regulation adopted by FDA, EU MDR, and other agencies.',
    markets: 'global',
    priority: 'high',
    appliesWhen: p => p.isSaMD,
    defaultChecklist: [
      'Confirm SaMD status: software performing a medical function without being part of a hardware device',
      'Classify per IMDRF risk framework: significance of information × state of healthcare situation (4 categories)',
      'Document intended medical purpose, intended users, and clinical workflow integration',
      'Establish SaMD quality management system per IMDRF N23 quality framework',
      'Define real-world performance monitoring plan: data collection, metrics, update triggers',
      'Document clinical validation strategy establishing analytical and clinical validity',
      'Prepare transparency documentation: algorithm description, training data, known limitations',
    ],
  },

  {
    id: 'fda-pccp',
    number: 'FDA PCCP Guidance (Jan 2025)',
    title: 'Predetermined Change Control Plan for AI/ML-Enabled Devices',
    category: 'Software',
    description: 'FDA final guidance enabling manufacturers to pre-specify algorithm modifications without a new 510(k) or PMA supplement per update. Requires a PCCP section in premarket submissions describing planned modifications, validation protocols, and change implementation methodology.',
    markets: ['us'],
    priority: 'medium',
    appliesWhen: p => p.isSaMD && p.hasAI && p.targetMarkets.includes('us'),
    defaultChecklist: [
      'Confirm PCCP eligibility: AI/ML algorithm component with iterative improvements planned',
      'Document modification protocol: scope and types of permitted algorithm changes',
      'Establish algorithm change protocol (ACP) with specific performance targets and boundaries',
      'Define testing and performance monitoring protocol for validating planned changes',
      'Document methodology for implementing approved changes without additional FDA submissions',
      'Establish real-world performance monitoring plan with defined update triggers',
      'Include PCCP as separate section in 510(k) or PMA premarket submission',
    ],
  },

  // ── Electrical ───────────────────────────────────────────────────────────

  {
    id: 'iec-60601-1',
    number: 'IEC 60601-1:2005+A2:2020',
    title: 'Medical electrical equipment — General requirements for basic safety and essential performance',
    category: 'Electrical',
    description: 'The foundational standard for active medical electrical equipment. Defines "basic safety" (freedom from physical hazards) and "essential performance" (clinical function required for intended use). All collateral standards (IEC 60601-1-X) and particular standards (IEC 60601-2-X) build on this base.',
    markets: 'global',
    priority: 'critical',
    appliesWhen: p => p.isActiveElectrical,
    defaultChecklist: [
      'Define essential performance — clinical functions where loss or degradation could cause harm',
      'Complete risk assessment for all basic safety and essential performance requirements (Clause 4)',
      'Conduct electrical safety testing: dielectric strength, leakage currents, earth continuity',
      'Verify mechanical safety: enclosure integrity, mechanical hazards, moving parts (Clause 9, 15)',
      'Conduct thermal safety assessment: abnormal operation and single-fault condition temperatures',
      'Classify applied parts (type B, BF, CF) based on patient contact risk',
      'Validate software/firmware per IEC 62304 if device contains software (Clause 14)',
      'Complete EMC testing per IEC 60601-1-2 collateral standard',
      'Conduct usability evaluation per IEC 62366-1 for all user interfaces',
      'Conduct testing under single-fault conditions for applicable hazards (Clause 13)',
    ],
  },

  {
    id: 'iec-60601-1-2',
    number: 'IEC 60601-1-2:2014 Edition 4.1 (2020)',
    title: 'Medical electrical equipment — EMC requirements and tests',
    category: 'Electrical',
    description: 'Collateral EMC standard using a risk-based approach requiring characterization of the intended electromagnetic environment (professional healthcare, home, special). Covers conducted/radiated emissions and multiple immunity phenomena including ESD, RF, surge, and voltage dips.',
    markets: 'global',
    priority: 'high',
    appliesWhen: p => p.isActiveElectrical,
    defaultChecklist: [
      'Define electromagnetic environment: professional healthcare, home healthcare, or special',
      'Complete radiated emissions testing (30 MHz–1 GHz) and conducted emissions (150 kHz–30 MHz) per CISPR 11',
      'Test ESD immunity: contact and air discharge per IEC 61000-4-2 at environment-appropriate levels',
      'Test radiated RF immunity per IEC 61000-4-3',
      'Test electrical fast transient/burst immunity per IEC 61000-4-4',
      'Test surge immunity (power and I/O ports) per IEC 61000-4-5',
      'Test conducted disturbance immunity per IEC 61000-4-6',
      'Test power frequency magnetic field immunity per IEC 61000-4-8',
      'Test voltage dips, short interruptions, and variations per IEC 61000-4-11',
      'Document EMC guidance in labeling/IFU: minimum separation distances from other equipment',
    ],
  },

  {
    id: 'iec-60601-1-8',
    number: 'IEC 60601-1-8:2006+A2:2020',
    title: 'Medical electrical equipment — Alarm systems',
    category: 'Electrical',
    description: 'Collateral standard for alarm systems in medical electrical equipment. Defines alarm signal properties, priorities (high/medium/low), inactivation states, and generation requirements. Critical for monitoring, ventilators, infusion pumps, and surgical equipment.',
    markets: 'global',
    priority: 'high',
    appliesWhen: p => p.isActiveElectrical && p.hasAlarms,
    defaultChecklist: [
      'Define all alarm conditions: physiological, technical, and advisory alarms',
      'Assign alarm priorities: high (immediate), medium (prompt), low (awareness)',
      'Specify auditory alarm characteristics: frequency, cadence, and volume ranges per priority',
      'Specify visual alarm characteristics: color coding (red=high, yellow=medium, cyan=advisory)',
      'Implement alarm inactivation states: audio off, pause (temporary), alarm signal disabled',
      'Ensure alarms cannot be permanently disabled without explicit deliberate user action',
      'Validate alarm audibility at required ambient noise levels for the intended environment',
      'Conduct usability validation of alarm recognition and response with representative users',
    ],
  },

  {
    id: 'iec-60601-1-11',
    number: 'IEC 60601-1-11:2015+A1:2020',
    title: 'Medical electrical equipment — Home healthcare environment requirements',
    category: 'Electrical',
    description: 'Collateral standard extending IEC 60601-1 for devices used in home healthcare. Specifies higher EMC immunity requirements, lay-user safety considerations, and drop testing from 1 m height for portable devices.',
    markets: 'global',
    priority: 'high',
    appliesWhen: p => p.isActiveElectrical && p.isHomeUse,
    defaultChecklist: [
      'Apply higher EMC immunity test levels applicable to residential electromagnetic environments',
      'Conduct drop testing from 1 m height for portable devices intended for home use',
      'Validate device usability with lay users (patients, caregivers) without medical training',
      'Assess labeling and IFU comprehension for a lay-user audience',
      'Evaluate risks of operation by users with physical or cognitive limitations',
      'Document transportation and storage conditions for home-environment distribution chain',
      'Verify mains supply voltage compatibility with residential supply range',
    ],
  },

  // ── Battery ───────────────────────────────────────────────────────────────

  {
    id: 'iec-62133',
    number: 'IEC 62133-2:2017',
    title: 'Secondary cells and batteries — Safety requirements for portable sealed secondary lithium cells',
    category: 'Battery',
    description: 'Safety standard for lithium-ion and lithium-polymer cells and batteries used in portable equipment. Tests cover abnormal charging, vibration, temperature extremes, and short circuit conditions. Required by major markets for devices using rechargeable lithium cells.',
    markets: 'global',
    priority: 'high',
    appliesWhen: p => p.hasBattery,
    defaultChecklist: [
      'Identify all rechargeable battery cells and battery management system (BMS) components',
      'Conduct continuous charging test — verify safe behavior under prolonged overcharge conditions',
      'Perform vibration testing per IEC 62133 vibration profile',
      'Conduct thermal abuse test: elevated temperature exposure',
      'Perform short circuit test at specified temperatures',
      'Validate BMS overcharge protection cut-off under overcharge conditions',
      'Perform forced discharge test for battery cells',
      'Validate battery enclosure mechanical integrity (crush, impact)',
      'Document UN 38.3 transportation classification for lithium cells',
      'Include battery warnings, replacement instructions, and disposal guidance in IFU/labeling',
    ],
  },

  // ── Biocompatibility ──────────────────────────────────────────────────────

  {
    id: 'iso-10993-1',
    number: 'ISO 10993-1:2018',
    title: 'Biological evaluation of medical devices — Framework and risk management process',
    category: 'Biocompatibility',
    description: 'Framework standard for biocompatibility evaluation. Defines a risk-based approach where testing extent is determined by contact category (surface, external communicating, implant) and duration (limited <24h, prolonged 24h–30d, permanent >30d). Chemical characterization may reduce animal testing.',
    markets: 'global',
    priority: 'critical',
    appliesWhen: p => p.hasPatientContact,
    defaultChecklist: [
      'Classify all patient-contacting materials by contact category and contact duration',
      'Conduct material chemical characterization per ISO 10993-18: identify and quantify leachables',
      'Perform toxicological risk assessment (TRA) for identified leachables vs. established thresholds',
      'Determine required biological tests from ISO 10993-1 Table A.1 contact classification matrix',
      'Confirm all testing conducted under GLP at ISO 17025-accredited or GLP-compliant labs',
      'Conduct cytotoxicity (ISO 10993-5), sensitization, and irritation tests (ISO 10993-10/23)',
      'Complete systemic toxicity assessment per ISO 10993-11 for prolonged/permanent contact',
      'Document biocompatibility evaluation report summarizing all chemical and biological findings',
    ],
  },

  {
    id: 'iso-10993-5',
    number: 'ISO 10993-5:2009',
    title: 'Biological evaluation — Tests for in vitro cytotoxicity',
    category: 'Biocompatibility',
    description: 'Defines in vitro test methods for evaluating cytotoxic potential of medical device materials. Three methods: extract test, direct contact, indirect contact. Required for virtually all patient-contacting materials. Testing conducted under GLP.',
    markets: 'global',
    priority: 'high',
    appliesWhen: p => p.hasPatientContact,
    defaultChecklist: [
      'Select cytotoxicity test method: extract test, direct contact, or indirect contact',
      'Prepare device extracts per ISO 10993-12 (extraction vehicle, conditions, surface area/volume ratio)',
      'Conduct cytotoxicity test using L-929 or MRC-5 cell lines',
      'Grade results on 0–4 scale; score ≤2 (slight reactivity) is typically acceptable',
      'Conduct GLP-compliant study at accredited laboratory with positive and negative controls',
      'Document test report: cell line source, passage number, culture conditions, and results',
    ],
  },

  {
    id: 'iso-10993-10',
    number: 'ISO 10993-10:2021',
    title: 'Biological evaluation — Tests for skin sensitization',
    category: 'Biocompatibility',
    description: 'Defines methods for evaluating sensitization potential (skin) and irritation. LLNA (local lymph node assay) is the preferred sensitization method. ISO 10993-23 (2021) now covers irritation testing as a separate part.',
    markets: 'global',
    priority: 'high',
    appliesWhen: p => p.hasPatientContact,
    defaultChecklist: [
      'Select sensitization test method: LLNA (preferred) or guinea pig maximization test (GPMT)',
      'Prepare device extracts per ISO 10993-12 using appropriate polar and non-polar solvents',
      'Conduct sensitization study under GLP at accredited laboratory',
      'Conduct irritation or intracutaneous reactivity study per ISO 10993-23',
      'Document dose selection rationale and vehicle selection',
      'Evaluate results against grading scale; document acceptability assessment',
    ],
  },

  {
    id: 'iso-10993-11',
    number: 'ISO 10993-11:2017',
    title: 'Biological evaluation — Tests for systemic toxicity',
    category: 'Biocompatibility',
    description: 'Defines testing for acute, sub-acute/subchronic, and chronic systemic toxicity. Required for devices with prolonged or permanent patient contact. Includes acute (single dose) and repeated-dose studies.',
    markets: 'global',
    priority: 'high',
    appliesWhen: p => p.hasPatientContact && (p.patientContactDuration === 'prolonged' || p.patientContactDuration === 'permanent'),
    defaultChecklist: [
      'Determine required systemic toxicity endpoints based on contact duration and route of exposure',
      'Conduct acute systemic toxicity study: intravenous or intraperitoneal injection in rodents',
      'Conduct sub-acute/subchronic toxicity study for prolonged contact (14–90 day repeated exposure)',
      'For permanent contact: assess chronic toxicity and potential carcinogenicity',
      'Evaluate pyrogenicity: bacterial endotoxin test (USP <85>) or in vivo rabbit pyrogen test',
      'Integrate findings with TRA for total extractable dose assessment',
    ],
  },

  {
    id: 'iso-10993-3',
    number: 'ISO 10993-3:2014',
    title: 'Biological evaluation — Tests for genotoxicity, carcinogenicity, and reproductive toxicity',
    category: 'Biocompatibility',
    description: 'Defines testing for genotoxicity (DNA damage/mutation), carcinogenicity, and reproductive toxicity. Required when chemical characterization indicates concerns, or for permanent implants with systemic exposure.',
    markets: 'global',
    priority: 'medium',
    appliesWhen: p => p.hasPatientContact && p.patientContactDuration === 'permanent',
    defaultChecklist: [
      'Review chemical characterization data for potential genotoxic impurities or carcinogens',
      'Conduct in vitro genotoxicity battery: bacterial reverse mutation (Ames) + mammalian cell test',
      'Conduct in vivo genotoxicity (micronucleus) study if in vitro results are positive or equivocal',
      'Assess carcinogenicity potential via literature review or rodent bioassay if indicated',
      'Assess reproductive/developmental toxicity if device contacts reproductive tissue or has systemic exposure',
      'Document all studies under GLP; document negative/positive control performance',
    ],
  },

  {
    id: 'iso-10993-4',
    number: 'ISO 10993-4:2017',
    title: 'Biological evaluation — Selection of tests for interactions with blood',
    category: 'Biocompatibility',
    description: 'Defines tests for blood-material interactions: thrombosis, coagulation, platelet activation, hematology, and complement activation. Required for devices that contact blood directly.',
    markets: 'global',
    priority: 'high',
    appliesWhen: p => p.bloodContact || p.patientContactType === 'implant',
    defaultChecklist: [
      'Classify blood contact: indirect extracorporeal, direct intravascular, or implant',
      'Select hemocompatibility tests per ISO 10993-4 Table 1 based on contact classification',
      'Conduct thrombogenicity assessment in relevant flow model',
      'Evaluate coagulation response: aPTT, prothrombin time',
      'Assess platelet activation: platelet count and activation markers (CD62P)',
      'Evaluate complement activation (C3a, C5a) for implantable/blood-contacting devices',
      'Conduct hematology assessment: complete blood count before and after device contact',
      'Document test conditions: anticoagulant type, blood source, contact duration, flow conditions',
    ],
  },

  {
    id: 'iso-10993-6',
    number: 'ISO 10993-6:2016',
    title: 'Biological evaluation — Tests for local effects after implantation',
    category: 'Biocompatibility',
    description: 'Defines methods for assessing local tissue effects after device implantation. Includes histopathological evaluation and quantitative grading of inflammatory response. Required for all implantable devices.',
    markets: 'global',
    priority: 'high',
    appliesWhen: p => p.isImplantable,
    defaultChecklist: [
      'Select implantation test model appropriate to device contact site (muscle, bone, subcutaneous)',
      'Conduct implantation study with negative control material (e.g., medical grade HDPE)',
      'Evaluate tissue response at multiple time points (4-week minimum; 12–26 weeks for permanent)',
      'Conduct histopathological analysis: inflammatory infiltrate, fibrous capsule, necrosis, calcification',
      'Grade tissue response per ISO 10993-6 Annex E grading scale',
      'Document implant site, geometry, and surgical technique in study report',
    ],
  },

  // ── Sterilization ─────────────────────────────────────────────────────────

  {
    id: 'iso-11135',
    number: 'ISO 11135:2014',
    title: 'Sterilization of health-care products — Ethylene oxide process requirements',
    category: 'Sterilization',
    description: 'Defines requirements for developing, validating, and controlling EO sterilization processes. Requires biological indicator-based qualification, residual EO testing per ISO 10993-7, and routine parametric release monitoring.',
    markets: 'global',
    priority: 'critical',
    appliesWhen: p => p.isSterile && p.sterilizationMethod === 'eo',
    defaultChecklist: [
      'Define sterilization process parameters: EO concentration, temperature, humidity, exposure time',
      'Conduct installation qualification (IQ) and operational qualification (OQ) of sterilizer',
      'Perform performance qualification (PQ): half-cycle and full-cycle studies with BIs (Bacillus atrophaeus)',
      'Establish EO residual limits per ISO 10993-7 for applicable device contact category and duration',
      'Conduct EO residual analysis post-sterilization; confirm adequacy of aeration',
      'Establish routine monitoring parameters: BI pass/fail and parametric release criteria',
      'Document sterilization batch records and establish annual requalification schedule',
    ],
  },

  {
    id: 'iso-11137',
    number: 'ISO 11137-1:2025',
    title: 'Sterilization of health-care products — Radiation sterilization requirements',
    category: 'Sterilization',
    description: 'Defines requirements for developing, validating, and controlling radiation sterilization (gamma, electron beam, X-ray). Requires dose setting, dosimetry, and routine release criteria achieving SAL 10⁻⁶.',
    markets: 'global',
    priority: 'critical',
    appliesWhen: p => p.isSterile && p.sterilizationMethod === 'radiation',
    defaultChecklist: [
      'Select sterilization method: gamma (Co-60), electron beam, or X-ray',
      'Determine bioburden per ISO 11737-1 from three consecutive product lots',
      'Select dose-setting method: VDmax (25 or 15 kGy) or bioburden/dose-response method',
      'Establish minimum and maximum sterilization doses based on dose-setting study',
      'Conduct dose mapping of product load to identify maximum/minimum dose zones',
      'Perform dose audit studies per ISO 11137-2 at defined intervals',
      'Assess radiation effects on device materials (polymer degradation, label adhesion)',
    ],
  },

  {
    id: 'iso-11607',
    number: 'ISO 11607-1:2019 / 11607-2:2019',
    title: 'Packaging for terminally sterilized medical devices',
    category: 'Sterilization',
    description: 'Two-part standard covering materials and sterile barrier systems (Part 1) and validation of forming, sealing, and assembly processes (Part 2). Ensures sterility maintenance through distribution to point of use.',
    markets: 'global',
    priority: 'high',
    appliesWhen: p => p.isSterile,
    defaultChecklist: [
      'Design sterile barrier system (SBS) maintaining device sterility to point of use',
      'Qualify packaging materials: microbial barrier, physical strength, sterilization compatibility',
      'Conduct package integrity testing: dye penetration, bubble emission, or seal strength testing',
      'Validate sealing process (IQ/OQ/PQ): seal strength, visual inspection, peel characteristics',
      'Conduct accelerated and real-time aging studies to establish shelf life (ISO 11607 + ASTM F1980)',
      'Perform distribution simulation per ASTM D4169 or ISTA protocols',
      'Validate aseptic opening: packaging can be opened without contaminating device',
    ],
  },

  // ── Clinical ─────────────────────────────────────────────────────────────

  {
    id: 'iso-14155',
    number: 'ISO 14155:2020',
    title: 'Clinical investigation of medical devices — Good clinical practice',
    category: 'Clinical',
    description: 'Defines GCP requirements for clinical investigations of medical devices. Covers protocol design, ethics oversight, informed consent, adverse event reporting, data integrity, and monitoring. FDA recognizes data collected per ISO 14155. Edition 4 expected 2026.',
    markets: 'global',
    priority: 'high',
    appliesWhen: () => true,
    defaultChecklist: [
      'Develop clinical investigation plan (CIP) with clear primary and secondary endpoints',
      'Define study design: randomized controlled trial, prospective single-arm, registry, etc.',
      'Obtain ethics committee (IRB/IEC) approval before enrolling any subjects',
      'Prepare informed consent forms meeting ISO 14155 requirements for all subject populations',
      'Define adverse event and serious adverse event (SAE) reporting timelines and procedures',
      'Establish data management plan: CRF design, query resolution, database lock procedures',
      'Develop statistical analysis plan (SAP) with pre-specified primary analysis method',
      'Establish monitoring plan: visit frequency, source data verification approach',
      'Document device accountability and investigational device supply chain controls',
    ],
  },

  // ── US FDA Regulations ────────────────────────────────────────────────────

  {
    id: '21cfr-820',
    number: '21 CFR 820 / QMSR (eff. Feb 2, 2026)',
    title: 'FDA Quality Management System Regulation',
    category: 'Market Regulatory',
    description: 'FDA GMP requirements. QSR replaced by QMSR effective February 2, 2026, incorporating ISO 13485:2016 by reference. Covers design controls, production controls, CAPA, supplier management, records, and complaint handling. All FDA-regulated device manufacturers must comply.',
    markets: ['us'],
    priority: 'critical',
    appliesWhen: p => p.targetMarkets.includes('us'),
    defaultChecklist: [
      'Establish QMS per QMSR (ISO 13485:2016): scope, quality manual, quality policy',
      'Implement design controls: inputs, outputs, reviews, verification, validation, transfer',
      'Establish supplier qualification and purchasing controls: qualified supplier list, incoming inspection',
      'Implement production and process controls: process validation, installation, servicing procedures',
      'Establish CAPA procedure: root cause identification, implementation, and effectiveness verification',
      'Establish MDR procedure for reportable adverse events and malfunctions (ref. 21 CFR 803)',
      'Conduct internal quality audits per scheduled plan; document findings and CAPAs',
      'Maintain Design History File (DHF), Device Master Record (DMR), and Device History Record (DHR)',
      'Prepare for FDA inspection per updated Quality System Inspection Technique (QSIT)',
    ],
  },

  {
    id: '21cfr-801',
    number: '21 CFR Part 801',
    title: 'FDA Device Labeling Requirements',
    category: 'Labeling',
    description: 'FDA labeling regulations requiring adequate directions for use, manufacturer identification, intended use, warnings, and UDI placement. All labeling must be truthful, not misleading, and consistent with cleared/approved indications.',
    markets: ['us'],
    priority: 'critical',
    appliesWhen: p => p.targetMarkets.includes('us'),
    defaultChecklist: [
      'Include device name, manufacturer name and address, and catalog/lot numbers on label',
      'Provide adequate directions for use: conditions, methods, contraindications, precautions',
      'Include all required warnings, cautions, and adverse effects (21 CFR 801.109 for Rx devices)',
      'Ensure all labeling claims are consistent with 510(k)/PMA cleared intended use',
      'Apply UDI on label and packaging: device identifier (DI) + production identifier (PI)',
      'Submit UDI data to GUDID (Global Unique Device Identification Database) per 21 CFR 830',
      'Ensure no false or misleading statements in labeling or promotional materials',
    ],
  },

  {
    id: '21cfr-803',
    number: '21 CFR Part 803',
    title: 'FDA Medical Device Reporting (MDR)',
    category: 'Market Regulatory',
    description: 'Requires manufacturers, importers, and user facilities to report adverse events involving medical devices. Manufacturers must report deaths, serious injuries, and certain malfunctions electronically via eMDR. Requires written MDR procedures and 2-year file retention.',
    markets: ['us'],
    priority: 'high',
    appliesWhen: p => p.targetMarkets.includes('us'),
    defaultChecklist: [
      'Establish written MDR procedure: event identification, evaluation, and reporting timeline',
      'Submit 30-day MDR for deaths and serious injuries caused or contributed to by device',
      'Submit 5-day MDR for events requiring immediate remedial action to prevent unreasonable risk',
      'Report device malfunctions likely to cause death/serious injury if they were to recur',
      'Maintain MDR event files for at least 2 years from date of event',
      'Submit reports electronically via FDA eMDR system (mandatory since August 2015)',
      'Establish internal escalation procedure for PMS data review and MDR determination',
    ],
  },

  {
    id: '21cfr-812',
    number: '21 CFR Part 812',
    title: 'Investigational Device Exemption (IDE)',
    category: 'Clinical',
    description: 'Allows investigational devices to be used in clinical studies before market clearance. Significant risk (SR) devices require FDA IDE approval; non-significant risk (NSR) devices require IRB approval only. Requires informed consent, safety monitoring, and records.',
    markets: ['us'],
    priority: 'high',
    appliesWhen: p => p.targetMarkets.includes('us'),
    defaultChecklist: [
      'Determine device risk classification: significant risk (SR) vs. non-significant risk (NSR)',
      'For SR devices: submit IDE application to FDA including protocol, risk analysis, consent forms',
      'For NSR devices: obtain IRB approval only; document the IRB risk determination',
      'Prepare IDE application: investigational plan, device description, manufacturing info, risk analysis',
      'Establish investigator agreements and confirm qualified investigator sites',
      'Implement device accountability: manufacturing, distribution, use, and return tracking',
      'Establish unanticipated device effect reporting to FDA and IRBs',
    ],
  },

  {
    id: '21cfr-830',
    number: '21 CFR Part 830',
    title: 'Unique Device Identification (UDI)',
    category: 'Labeling',
    description: 'Requires medical device labels to bear a UDI consisting of a device identifier (DI) and production identifier (PI). Manufacturers must submit device data to FDA\'s GUDID database. Phased implementation by class (Class III first, Class I last).',
    markets: ['us'],
    priority: 'high',
    appliesWhen: p => p.targetMarkets.includes('us'),
    defaultChecklist: [
      'Obtain FDA-accredited UDI issuing agency (GS1, HIBCC, or ICCBBA) and assign device identifier (DI)',
      'Design label to include both human-readable interpretation (HRI) and AIDC (barcode or 2D matrix)',
      'For Class III: include production identifiers (lot/batch, serial, mfg date, expiry) on label',
      'Submit device identification data to GUDID for all versions and configurations',
      'For reusable devices requiring direct marking: apply UDI directly on device per class requirements',
      'Maintain GUDID data; update for any device changes affecting DI or labeling',
    ],
  },

  // ── EU ────────────────────────────────────────────────────────────────────

  {
    id: 'eu-mdr',
    number: 'EU MDR 2017/745',
    title: 'EU Medical Devices Regulation',
    category: 'Market Regulatory',
    description: 'EU regulation governing all non-IVD medical devices. Requires CE marking, classification per 22 rules (Class I/IIa/IIb/III), Notified Body involvement for Class IIa+, clinical evaluation, EUDAMED registration, and post-market surveillance. EUDAMED fully mandatory May 28, 2026.',
    markets: ['eu'],
    priority: 'critical',
    appliesWhen: p => p.targetMarkets.includes('eu') && !p.isIVD,
    defaultChecklist: [
      'Classify device per MDR Annex VIII classification rules (Rules 1–22)',
      'Prepare and maintain technical documentation per MDR Annex II (design, manufacture, PMS, clinical)',
      'Conduct clinical evaluation per MDR Article 61 and MEDDEV 2.7/1 Rev 4; maintain CER',
      'Implement PMS plan and post-market clinical follow-up (PMCF) plan',
      'Register manufacturer and device in EUDAMED (mandatory from May 28, 2026)',
      'For Class IIa+: engage accredited Notified Body for conformity assessment audit',
      'Assign EU UDI; register in EUDAMED UDI database and label per MDR Article 27',
      'Prepare Declaration of Conformity (DoC) signed by authorized EU representative',
      'Establish vigilance procedure: serious incident reporting to national competent authority',
      'Issue Periodic Safety Update Reports (PSURs): annually for Class IIa+; PMS report for Class I',
    ],
  },

  {
    id: 'eu-ivdr',
    number: 'EU IVDR 2017/746',
    title: 'EU In Vitro Diagnostics Regulation',
    category: 'Market Regulatory',
    description: 'EU regulation for IVD devices. Classification Classes A–D based on risk. Class C and D require Notified Body. Significant increase in clinical evidence vs. predecessor IVDD. Class D deadline Dec 31, 2027; Class C deadline Dec 31, 2028.',
    markets: ['eu'],
    priority: 'critical',
    appliesWhen: p => p.targetMarkets.includes('eu') && p.isIVD,
    defaultChecklist: [
      'Classify IVD per IVDR Annex VIII classification rules (Class A, B, C, D)',
      'Conduct performance evaluation: analytical performance, clinical performance, scientific validity',
      'For Class B/C/D: engage Notified Body (Class C by Dec 31, 2028; Class D by Dec 31, 2027)',
      'Register device in EUDAMED; assign IVD UDI and submit to EUDAMED UDI database',
      'Implement post-market performance follow-up (PMPF) plan for ongoing evidence collection',
      'Issue periodic safety update reports (PSURs) as required by class',
      'Prepare Declaration of Conformity and CE marking per IVDR conformity assessment procedure',
    ],
  },

  {
    id: 'meddev-271',
    number: 'MEDDEV 2.7/1 Rev. 4',
    title: 'EU Clinical Evaluation — Guidance for Manufacturers and Notified Bodies',
    category: 'Clinical',
    description: 'European Commission guidance on clinical evaluation under MDR. Defines methodology for systematic literature review, state-of-the-art determination, equivalence claims, and benefit-risk assessment. Notified Body will scrutinize the Clinical Evaluation Report (CER) methodology.',
    markets: ['eu'],
    priority: 'high',
    appliesWhen: p => p.targetMarkets.includes('eu'),
    defaultChecklist: [
      'Define clinical evaluation scope: intended purpose, target population, and clinical claims',
      'Conduct systematic literature search using ≥2 databases (PubMed + Embase or Cochrane)',
      'Document literature appraisal: relevance, quality, and contribution to clinical evidence',
      'Determine state of the art for the disease/condition and available treatments/alternatives',
      'Assess equivalence to predicate device if applicable: clinical, technical, biological equivalence',
      'Perform benefit-risk assessment: benefits vs. residual risks vs. state of the art',
      'Document clinical evaluation report (CER) with traceability to each piece of clinical evidence',
      'Define PMCF plan for ongoing evidence generation; plan periodic CER updates',
    ],
  },

  // ── Other Markets ─────────────────────────────────────────────────────────

  {
    id: 'canada-sor',
    number: 'SOR/98-282',
    title: 'Canada Medical Devices Regulations (Health Canada)',
    category: 'Market Regulatory',
    description: 'Health Canada\'s regulations governing medical devices. Four device classes (I–IV). Class I: establishment registration only (no device licence). Class II–IV: Medical Device Licence (MDL) required. QMS per ISO 13485. Bilingual (English/French) labeling required.',
    markets: ['canada'],
    priority: 'critical',
    appliesWhen: p => p.targetMarkets.includes('canada'),
    defaultChecklist: [
      'Classify device per Health Canada classification rules (Class I–IV)',
      'For Class I: register establishment with Health Canada (no device licence required)',
      'For Class II–IV: obtain Medical Device Licence by submitting application with technical dossier',
      'Establish QMS per ISO 13485 (Health Canada recognizes ISO 13485 certification)',
      'Prepare bilingual labeling (English and French) compliant with SOR/98-282',
      'For Class III/IV: provide clinical evidence from Canadian or recognized international trials',
      'Establish adverse event reporting procedure for mandatory problem reporting to Health Canada',
    ],
  },

  {
    id: 'japan-pmda',
    number: 'PMD Act / Japan QMS Ministerial Ordinance No. 169',
    title: 'Japan Medical Device Approval (PMDA/MHLW)',
    category: 'Market Regulatory',
    description: 'Japan\'s regulatory framework under the PMD Act. PMDA reviews Class III (Shonin PMA) and Class IV (higher-risk PMA) devices. Japan QMS Ordinance mirrors ISO 13485 with Japan-specific additions. Post-market surveillance (PMS) via MID-NET for 4–7 years.',
    markets: ['japan'],
    priority: 'critical',
    appliesWhen: p => p.targetMarkets.includes('japan'),
    defaultChecklist: [
      'Classify device per Japan classification system (Class I–IV) and Japanese listing code',
      'For Class II: obtain 3rd-party certification from Designated Certification Body (DCB)',
      'For Class III/IV: submit Shonin pre-market approval application to PMDA/MHLW',
      'Establish Japan QMS Ordinance No. 169 compliant quality system (aligned with ISO 13485)',
      'Conduct PMDA Pre-submission Consultation (PSC) before formal application for novel devices',
      'Prepare Japanese-language labeling and IFU compliant with PMD Act requirements',
      'Appoint Marketing Authorization Holder (MAH) — must be Japan-based entity',
      'Establish PMS plan: periodic reports for 4–7 years per risk class',
    ],
  },

  {
    id: 'australia-tga',
    number: 'Therapeutic Goods Act / Medical Devices Regulations 2002',
    title: 'Australia TGA — ARTG Registration',
    category: 'Market Regulatory',
    description: 'TGA regulates medical devices via the Australian Register of Therapeutic Goods (ARTG). Device classes align broadly with EU classification. Class IIb and III require TGA audit or Notified Body evidence. Australian Sponsor must be a locally registered entity.',
    markets: ['australia'],
    priority: 'critical',
    appliesWhen: p => p.targetMarkets.includes('australia'),
    defaultChecklist: [
      'Classify device per TGA classification rules (Class I, IIa, IIb, III, AIMD)',
      'For Class I: submit self-declaration ARTG application with conformity assessment evidence',
      'For Class IIb+: submit TGA conformity assessment or provide Notified Body audit report',
      'Register Australian Sponsor (must be Australia-based entity) for ARTG entry',
      'Submit ARTG application via TGA Business Services portal with technical evidence',
      'Comply with TGA English-language labeling requirements including manufacturer address',
      'Establish adverse event reporting procedure: mandatory reporting to TGA within specified timeframes',
    ],
  },

  {
    id: 'brazil-anvisa',
    number: 'RDC 751/2022 / RDC 830/2023',
    title: 'Brazil ANVISA Medical Device Registration',
    category: 'Market Regulatory',
    description: 'ANVISA regulates medical devices (Class I–IV; 22 classification rules). Class I/II: Notificação (no review). Class III/IV: Registro (ANVISA review). Brazilian GMP (B-GMP) audit mandatory. Portuguese-language labeling required.',
    markets: ['brazil'],
    priority: 'critical',
    appliesWhen: p => p.targetMarkets.includes('brazil'),
    defaultChecklist: [
      'Classify device per ANVISA RDC 751/2022 classification rules (Class I–IV, 22 rules)',
      'For Class I/II: submit Notificação via DATAVISA system',
      'For Class III/IV: submit Registro application to ANVISA for review',
      'Appoint Brazilian Company (local legal partner) as regulatory representative',
      'Obtain Brazilian GMP certificate (B-GMP): factory inspection by ANVISA or accredited body',
      'Prepare Portuguese-language technical dossier per ANVISA format requirements',
      'Establish pharmacovigilance procedure for ANVISA adverse event reporting',
    ],
  },

  {
    id: 'uk-mhra',
    number: 'UK MDR 2002 / MHRA Guidance',
    title: 'UK MHRA — UKCA Marking and Post-Brexit Registration',
    category: 'Market Regulatory',
    description: 'Post-Brexit UK framework. CE marked devices accepted until June 2028 (Class IIb implants) or June 2030 (others). MHRA has proposed UDI-based registration and international reliance pathways. Northern Ireland: EU MDR continues to apply.',
    markets: ['uk'],
    priority: 'high',
    appliesWhen: p => p.targetMarkets.includes('uk'),
    defaultChecklist: [
      'Determine transition pathway: CE marking accepted until June 2028/2030 depending on device class',
      'For Northern Ireland: EU MDR continues to apply; CE marking valid for NI market',
      'Register with MHRA as manufacturer or UK Responsible Person before placing on GB market',
      'For UKCA marking: engage UK Approved Body (equivalent of Notified Body) for Class IIa+',
      'Comply with UK MDR 2002 labeling requirements including UK Responsible Person address',
      'Monitor MHRA guidance on proposed UDI-based registration system (expected 2025–2026)',
      'Establish adverse event reporting procedure: report to MHRA within MDR-equivalent timelines',
    ],
  },

  // ── Cybersecurity ─────────────────────────────────────────────────────────

  {
    id: 'fda-cybersecurity',
    number: 'FDA Cybersecurity Guidance (June 2025)',
    title: 'Cybersecurity in Medical Devices — Premarket Submissions Content',
    category: 'Cybersecurity',
    description: 'FDA guidance implementing Section 524B cybersecurity requirements. Requires threat modeling, SBOM, vulnerability testing, and post-market monitoring plans in premarket submissions. Applies to any networked or software-driven device marketed in the US.',
    markets: ['us'],
    priority: 'high',
    appliesWhen: p => p.targetMarkets.includes('us') && p.isNetworked,
    defaultChecklist: [
      'Conduct threat modeling (STRIDE or equivalent) for all network interfaces and attack surfaces',
      'Implement secure software development lifecycle (Secure SDLC) with security requirements',
      'Generate and maintain Software Bill of Materials (SBOM) listing all software components',
      'Conduct vulnerability scanning and penetration testing on device software and communications',
      'Implement authentication, authorization, and access control mechanisms',
      'Implement encryption for data at rest and in transit (AES-256, TLS 1.2+)',
      'Establish vulnerability disclosure policy and coordinated vulnerability disclosure (CVD) process',
      'Establish patch/update mechanism for security vulnerabilities throughout device lifecycle',
      'Include cybersecurity information in premarket submission: threat model, SBOM, testing summary',
      'Define post-market cybersecurity monitoring plan with 30-day critical vulnerability target',
    ],
  },

  {
    id: 'fcc-part15',
    number: 'FCC Part 15 / Part 18',
    title: 'FCC Radio Frequency Device Authorization',
    category: 'Cybersecurity',
    description: 'FCC regulations for unintentional (Part 15) and intentional (Part 18 ISM) RF emitters. Required for any device marketed in the US generating or using radio frequency energy. FCC ID authorization required for intentional radiators (WiFi, Bluetooth, cellular).',
    markets: ['us'],
    priority: 'medium',
    appliesWhen: p => p.targetMarkets.includes('us') && (p.isActiveElectrical || p.isNetworked),
    defaultChecklist: [
      'Determine FCC applicability: Part 15 (unintentional emitter) or Part 18 (ISM intentional radiator)',
      'For intentional radiators (WiFi, Bluetooth, cellular): obtain FCC ID via accredited TCB',
      'For unintentional emitters: conduct FCC Part 15 Subpart B radiated/conducted emissions testing',
      'Test radiated emissions at FCC-accredited laboratory (Class B limits for residential use)',
      'Apply FCC label with FCC ID on device if intentional radiator',
      'Include FCC compliance statement in user manual / labeling',
      'Assess SAR if device transmits RF near user body',
    ],
  },

  // ── Privacy / HIPAA ──────────────────────────────────────────────────────────
  {
    id: 'hipaa-security',
    number: '45 CFR §§164.302–318',
    title: 'HIPAA Security Rule — ePHI Safeguards',
    category: 'Privacy',
    description: 'Mandates administrative, physical, and technical safeguards for electronic protected health information (ePHI). Applies to any SaMD, cloud-connected device, or health IT platform that creates, receives, maintains, or transmits ePHI. Security Risk Analysis (SRA) is the cornerstone requirement.',
    markets: ['us'],
    priority: 'critical',
    appliesWhen: (p) => p.targetMarkets.includes('us') && (p.isSaMD || p.isNetworked),
    defaultChecklist: [
      'Conduct Security Risk Analysis (SRA): identify all ePHI, threats, vulnerabilities, likelihood and impact',
      'Develop Security Risk Management Plan addressing identified risks with implementation timelines',
      'Implement access control: unique user IDs, emergency access procedure, automatic logoff, encryption',
      'Establish audit controls: record and examine activity in systems containing ePHI (§164.312(b))',
      'Implement integrity controls: mechanisms to authenticate that ePHI has not been altered or destroyed',
      'Implement transmission security: encryption of ePHI in transit (TLS 1.2+ minimum)',
      'Conduct workforce security training; establish sanction policy for non-compliance',
      'Execute Business Associate Agreement (BAA) with all third-party ePHI processors',
      'Establish contingency plan: data backup, disaster recovery, emergency mode operations',
      'Document all policies and procedures; review and update at least annually',
    ],
  },
  {
    id: 'hipaa-privacy',
    number: '45 CFR §§164.500–534',
    title: 'HIPAA Privacy Rule — PHI Use and Disclosure',
    category: 'Privacy',
    description: 'Establishes national standards for protecting individually identifiable health information (PHI). Requires patient authorization for non-treatment uses, minimum necessary standard, patient rights to access/amend records, and breach notification within 60 days. Applies to covered entities and business associates.',
    markets: ['us'],
    priority: 'high',
    appliesWhen: (p) => p.targetMarkets.includes('us') && (p.isSaMD || p.isNetworked),
    defaultChecklist: [
      'Identify all PHI handled: created, received, maintained, or transmitted by the device/platform',
      'Apply minimum necessary standard: limit PHI use/disclosure to the minimum reasonably necessary',
      'Establish patient rights procedures: access, amendment, accounting of disclosures, and restrictions',
      'Prepare and distribute HIPAA-compliant Notice of Privacy Practices (NPP)',
      'Establish breach notification procedure: notify affected individuals ≤60 days; report to HHS',
      'Train workforce on Privacy Rule requirements; document completion with signed acknowledgments',
      'Appoint Privacy Officer responsible for ongoing Privacy Rule compliance',
      'Implement de-identification procedures per Safe Harbor or Expert Determination method (§164.514)',
    ],
  },
  {
    id: 'hitech',
    number: 'HITECH Act (42 U.S.C. § 17932)',
    title: 'HITECH Act — Breach Notification and BA Liability',
    category: 'Privacy',
    description: 'Strengthened HIPAA enforcement, extended Security Rule obligations directly to business associates, and increased civil penalties to $1.9M/violation category/year. Requires breach risk assessment using 4-factor test. Encryption provides safe harbor from breach notification obligations.',
    markets: ['us'],
    priority: 'high',
    appliesWhen: (p) => p.targetMarkets.includes('us') && (p.isSaMD || p.isNetworked),
    defaultChecklist: [
      'Execute Business Associate Agreements (BAAs) with all covered entity and sub-BA partners',
      'Implement 4-factor breach risk assessment: nature of PHI, unauthorized person, whether accessed, risk mitigation',
      'Implement encryption as safe harbor: AES-256 at rest, TLS 1.2+ in transit renders PHI "secured"',
      'Report breaches of unsecured PHI to HHS and affected individuals within required timelines',
      'Ensure sub-contractors (sub-BAs) are contractually bound to same HIPAA Security obligations',
      'Document all compliance activities; maintain records minimum 6 years for HHS audit readiness',
    ],
  },
  {
    id: 'soc2',
    number: 'AICPA SOC 2 Type II',
    title: 'SOC 2 Type II — Cloud Security and Availability',
    category: 'Privacy',
    description: 'Independent third-party audit of controls for security, availability, processing integrity, confidentiality, and privacy for cloud-hosted SaMD and health platforms. Type II covers a 6-month+ observation period. Required by major health system buyers, payers, and enterprise customers.',
    markets: ['us', 'uk', 'canada', 'australia'],
    priority: 'high',
    appliesWhen: (p) => p.isSaMD && p.isNetworked && (p.targetMarkets.includes('us') || p.targetMarkets.includes('uk') || p.targetMarkets.includes('canada') || p.targetMarkets.includes('australia')),
    defaultChecklist: [
      'Define system description: infrastructure, software, processes, and people in scope',
      'Select Trust Services Criteria (TSC): Security (CC) required; add Availability, Confidentiality, Privacy as needed',
      'Engage accredited CPA firm (e.g., Deloitte, EY, Drata-auditor) for Type II engagement',
      'Implement CC6.1–CC9.2 Common Criteria: logical access, encryption, change management, monitoring',
      'Implement availability controls: uptime SLAs, disaster recovery, incident response procedures',
      'Conduct SOC 2 readiness assessment (gap analysis) 3–6 months before formal audit window opens',
      'Run 6-month observation period with continuous evidence collection (screenshots, logs, reviews)',
      'Receive final Type II report; share under NDA with customers; publish summary on trust page',
      'Plan annual re-certification to maintain current SOC 2 status',
    ],
  },
  {
    id: 'ansi-aami-tir57',
    number: 'ANSI/AAMI TIR57:2016+A1:2019',
    title: 'ANSI/AAMI TIR57 — Privacy Architecture for Networked Medical Devices',
    category: 'Privacy',
    description: 'AAMI Technical Information Report providing guidance on privacy by design for networked medical devices. Defines a privacy risk management process mirroring ISO 14971 in structure, covering data minimization, consent, de-identification, and PHI lifecycle. Referenced in FDA connected device pre-market guidance.',
    markets: 'global',
    priority: 'medium',
    appliesWhen: (p) => p.isNetworked && (p.isSaMD || p.hasAI),
    defaultChecklist: [
      'Conduct privacy risk assessment: identify all personal data flows, threats, and applicable regulations',
      'Apply data minimization: collect only PHI/PII strictly necessary for the intended medical purpose',
      'Define consent model and patient rights: access, correction, deletion where applicable by jurisdiction',
      'Implement de-identification per HIPAA Safe Harbor or Expert Determination method',
      'Document privacy architecture: data flow diagrams showing all PHI entry, storage, and exit points',
      'Include privacy notice and data handling information in device labeling and IFU',
      'Align privacy risk management file with ISO 14971 risk management file for traceability',
    ],
  },

  // ── Safety Certification ──────────────────────────────────────────────────────

  {
    id: 'ul-60601-1',
    number: 'UL 60601-1',
    title: 'UL Medical Electrical Equipment — Safety Listing (NRTL)',
    category: 'Safety Certification',
    description: 'UL Listing for medical electrical equipment based on IEC/ANSI/AAMI ES60601-1 with US (SB 2) and Canadian (CSA C22.2 No. 60601-1) deviations. Required by virtually all US hospital purchasing policies as an OSHA-recognized NRTL mark. Includes annual Follow-Up Service (FUS) factory inspections.',
    markets: ['us', 'canada'],
    priority: 'high',
    appliesWhen: (p) => p.isActiveElectrical && (p.targetMarkets.includes('us') || p.targetMarkets.includes('canada')),
    defaultChecklist: [
      'Engage UL or OSHA-recognized NRTL (CSA, TÜV, Intertek) for product certification engagement',
      'Submit device for evaluation against UL 60601-1 including US National Deviations (SB 2) and Canadian deviations',
      'Address ANSI/AAMI ES60601-1:2005+A2:2021 deviations: 120V/60Hz, Hospital Grade power cord, insulation coordination',
      'Resolve all non-conformances identified during UL evaluation before mark is authorized',
      'Apply cULus Mark (or cUL / UL as appropriate) to production device label',
      'Maintain Factory Follow-Up Service (FUS): submit to annual unannounced UL factory inspections',
      'Submit design changes affecting Listed product to UL before production implementation',
    ],
  },
  {
    id: 'ul-2900',
    number: 'UL 2900-2-1:2019',
    title: 'UL Cybersecurity Assurance — Network-Connectable Medical Devices',
    category: 'Safety Certification',
    description: 'UL standard for software cybersecurity of network-connectable medical devices. Covers binary analysis, known vulnerability testing (CVE), structured penetration testing, and security controls assessment. UL CAP (Cybersecurity Assurance Program) provides listing. Referenced in FDA pre/post-market cybersecurity guidance.',
    markets: ['us'],
    priority: 'high',
    appliesWhen: (p) => p.targetMarkets.includes('us') && p.isNetworked,
    defaultChecklist: [
      'Conduct binary and source code analysis for software weaknesses per CWE Top 25',
      'Perform CVE vulnerability scan on all software components (SBOM-driven)',
      'Conduct structured penetration testing per UL 2900-2-1 test methodology and scope',
      'Validate authentication and authorization mechanisms under adversarial test conditions',
      'Verify cryptography: no prohibited algorithms (MD5, SHA-1, DES, 3DES); TLS 1.2+ mandatory',
      'Test software supply chain integrity: verify third-party components against SBOM',
      'Submit test evidence package to UL for CAP certification review',
      'Establish ongoing vulnerability monitoring and patch deployment process post-certification',
    ],
  },
  {
    id: 'ansi-aami-es60601',
    number: 'ANSI/AAMI ES60601-1:2005+A2:2021',
    title: 'ANSI/AAMI Medical Electrical Equipment — US National Adoption',
    category: 'Safety Certification',
    description: 'US national adoption of IEC 60601-1 with North American deviations addressing 120V/60Hz supply voltage, receptacle types, Hospital Grade cord requirements, and specific performance deviations. Required basis for UL and CSA product listing. Recognized by FDA under multiple device product codes.',
    markets: ['us', 'canada'],
    priority: 'high',
    appliesWhen: (p) => p.isActiveElectrical && (p.targetMarkets.includes('us') || p.targetMarkets.includes('canada')),
    defaultChecklist: [
      'Identify applicable ANSI/AAMI ES60601-1 national deviations from IEC 60601-1 for device type',
      'Verify mains supply compatibility: 120V ±10% / 60Hz with 15A NEMA 5-15 receptacle',
      'Apply Hospital Grade power cord (green dot marking) for devices used in patient vicinity',
      'Address insulation coordination deviations: adjust creepage/clearance for 120V operation vs. 230V',
      'Confirm power interruption immunity for essential performance (ANSI/AAMI ES60601-1 Annex requirement)',
      'Reference ANSI/AAMI ES60601-1 alongside IEC 60601-1 in technical documentation and test reports',
      'Verify device label includes required North American safety marks and certification markings',
    ],
  },

  // ── Additional Software / Cybersecurity ───────────────────────────────────────

  {
    id: '21cfr-11',
    number: '21 CFR Part 11',
    title: 'FDA Electronic Records and Electronic Signatures',
    category: 'Software',
    description: 'FDA regulation governing electronic records and electronic signatures used in lieu of paper records for regulated device activities. Applies to DHR, DMR, complaint records, CAPA records, and audit trails maintained in electronic systems. Requires computer system validation and non-repudiation.',
    markets: ['us'],
    priority: 'medium',
    appliesWhen: (p) => p.targetMarkets.includes('us') && p.hasSoftware,
    defaultChecklist: [
      'Identify all electronic records substituting for paper records under 21 CFR Parts 820/803/812',
      'Validate computer systems per GAMP 5 methodology: IQ/OQ/PQ with documented test scripts',
      'Implement user access controls: unique user IDs, role-based access, password controls',
      'Implement audit trails: computer-generated, time-stamped records of operator actions; cannot be altered',
      'Implement electronic signature controls: two distinct identification components (ID + password/biometric)',
      'Establish periodic backup and recovery procedures for all records under Part 11 scope',
      'Document system validation package; maintain validation status with change control procedure',
    ],
  },
  {
    id: 'iec-62443-4-2',
    number: 'IEC 62443-4-2:2019',
    title: 'Industrial Security — Component Security Requirements (Medical Application)',
    category: 'Cybersecurity',
    description: 'Defines technical security requirements for network-connectable embedded devices, software applications, and host components. Security Level targets (SL 1–4) determine requirement rigor. Referenced in FDA cybersecurity guidance and ENISA medical device cybersecurity guidelines. Complements IEC 62304 for secure development lifecycle.',
    markets: 'global',
    priority: 'medium',
    appliesWhen: (p) => p.isNetworked && p.hasSoftware,
    defaultChecklist: [
      'Identify Security Level target (SL-C 1–4) based on threat model and consequence of compromise',
      'Implement CR 1.1–1.14: identification and authentication controls for all users and devices',
      'Implement CR 2.1–2.12: use control — enforce least privilege, session lock, remote session termination',
      'Implement CR 3.1–3.9: system integrity — communication integrity, malicious code protection, patching',
      'Implement CR 4.1–4.3: data confidentiality — protect sensitive data at rest and in transit',
      'Implement CR 5.1–5.2: restricted data flow — network segmentation and zone boundary protection',
      'Implement CR 6.1–6.2: timely event response — audit log capacity and continuous monitoring',
      'Implement CR 7.1–7.8: resource availability — DoS protection, backup/restore, emergency power',
      'Document security requirements traceability from threat model through implemented controls to test evidence',
    ],
  },
];

export function getApplicableStandards(profile: DeviceProfile): StandardDef[] {
  return STANDARDS.filter(s => s.appliesWhen(profile));
}

export const CATEGORY_META: Record<StandardCategory, { color: string; bg: string }> = {
  'QMS':               { color: '#2a5fa0', bg: 'rgba(42,95,160,0.12)'   },
  'Risk':              { color: '#8a3030', bg: 'rgba(138,48,48,0.12)'   },
  'Software':          { color: '#6a4a9a', bg: 'rgba(106,74,154,0.12)'  },
  'Electrical':        { color: '#1e7a5a', bg: 'rgba(30,122,90,0.12)'   },
  'Battery':           { color: '#7a5a10', bg: 'rgba(122,90,16,0.12)'   },
  'Biocompatibility':  { color: '#3a7a30', bg: 'rgba(58,122,48,0.12)'   },
  'Sterilization':     { color: '#5a3a7a', bg: 'rgba(90,58,122,0.12)'   },
  'Usability':         { color: '#7a4a20', bg: 'rgba(122,74,32,0.12)'   },
  'Clinical':          { color: '#20607a', bg: 'rgba(32,96,122,0.12)'   },
  'Labeling':          { color: '#6a7a20', bg: 'rgba(106,122,32,0.12)'  },
  'Market Regulatory': { color: '#9a4a20', bg: 'rgba(154,74,32,0.12)'   },
  'Cybersecurity':     { color: '#4a3a7a', bg: 'rgba(74,58,122,0.12)'   },
  'Privacy':              { color: '#2a7a6a', bg: 'rgba(42,122,106,0.12)'  },
  'Safety Certification': { color: '#7a6a2a', bg: 'rgba(122,106,42,0.12)'  },
};

export const MARKET_META: Record<TargetMarket, { label: string }> = {
  us:        { label: 'US'  },
  eu:        { label: 'EU'  },
  japan:     { label: 'JP'  },
  canada:    { label: 'CA'  },
  australia: { label: 'AU'  },
  brazil:    { label: 'BR'  },
  uk:        { label: 'UK'  },
};
