import { authkitMiddleware } from "@workos-inc/authkit-nextjs";

export default authkitMiddleware({
  middlewareAuth: {
    enabled: true,
    unauthenticatedPaths: [
      "/",
      "/login",
      "/callback",
      "/landing1",
      "/landing3",
      "/home",
      "/algorithmlab",
      "/biodesign",
      "/biodesign/share/(.*)",
      "/api/biodesign/share/(.*)",
      "/invest",
      "/pureburger",
      "/digitalhealth",
      "/digitalhealth/(.*)",
      "/moneymatrix",
      "/moneymatrix/(.*)",
      "/samd",
      "/samd/(.*)",
      "/umn",
      "/pitchdecklab",
      "/pitchdecklab/(.*)",
      "/mobilelab",
      "/mobile",
      "/mobile/(.*)",
      "/engineering",
      "/bi",
      "/datascience",
      "/colors",
      "/brand",
      "/gapanalysis",
      "/contractlab",
      "/backgroundlab",
      "/accelerate",
      "/accelerate/(.*)",
      "/api/accelerate/(.*)",
      "/mn",
      "/cloud",
      "/firmware",
      "/webapp",
      "/mechanical",
      "/bom",
      "/control",
      "/apparchive",
      "/archive",
      "/api/push/(.*)",
    ],
  },
  redirectUri: process.env.NEXT_PUBLIC_WORKOS_REDIRECT_URI,
});

export const config = {
  matcher: ["/((?!_next|favicon.ico|icon-.*|manifest\.json|.*\..*).*)"],
};
